services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    # Override the Dockerfile command
    command: bash -c "npm ci && npm run start:dev"
    ports:
      - 3000:3000
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
    networks:
      - fiap
    depends_on:
      - db
  db:
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'db-data:/var/lib/mysql'
    networks:
      - fiap
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  pubsub: 
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    container_name: pubsub
    command: bash -c "gcloud beta emulators pubsub start --project=${GCP_PROJECT_ID} --host-port='0.0.0.0:8085'"
    networks:
      - fiap
    ports:
      - "8085:8085"

  pagamentos-db:
    # image: firebase-emulator:2.2
    image: pmoon1993/firebase-emulator:2.2
    command: firebase emulators:start --project ${GCP_PROJECT_ID}
    networks:
      - fiap
    ports:
      - "4000:4000"
      - "8090:8090" 

networks:
  fiap:

volumes:
  db-data:
    driver: local
